// FROZEN MERGE SEAM — single source of truth. DESIGN imports, never edits. Do not modify field names/enums.
// ============================================================
// src/types/tokens.ts  —  FROZEN. (§11 DESIGN-TOKEN KEYS)
// Code owns KEYS, design owns VALUES. Code only ever writes var(--cph-...).
// All keys are CSS custom properties under :root; the three OS themes override
// the SAME keys under [data-os="linux"|"windows"|"ad"].
// ============================================================
export const TOKEN_KEYS = {
  color: [
    '--cph-color-bg',
    '--cph-color-surface',
    '--cph-color-surface-raised',
    '--cph-color-border',
    '--cph-color-text',
    '--cph-color-text-muted',
    '--cph-color-primary',
    '--cph-color-primary-contrast',
    '--cph-color-accent',
    '--cph-color-focus',
    '--cph-color-danger',
    '--cph-color-success',
  ],
  octo: [
    '--cph-octo-idle',
    '--cph-octo-greeting',
    '--cph-octo-listening',
    '--cph-octo-thinking',
    '--cph-octo-found',
    '--cph-octo-empty',
    '--cph-octo-copied',
    '--cph-octo-error',
    '--cph-octo-celebrate',
    '--cph-octo-ink',
    '--cph-octo-glow',
    '--cph-octo-tint',
  ],
  severity: [
    '--cph-sev-info',
    '--cph-sev-low',
    '--cph-sev-medium',
    '--cph-sev-high',
    '--cph-sev-critical',
  ],
  variable: ['--cph-var-set', '--cph-var-unset', '--cph-var-invalid', '--cph-var-token-bg'],
  confidence: ['--cph-confidence-verified', '--cph-confidence-unverified'],
  copy: ['--cph-copy-success', '--cph-copy-flash'],
  node: [
    '--cph-node-recon',
    '--cph-node-enum',
    '--cph-node-exploit',
    '--cph-node-privesc',
    '--cph-node-lateral',
    '--cph-node-persistence',
    '--cph-node-outcome',
    '--cph-node-decision',
  ],
  elevation: [
    '--cph-elev-0',
    '--cph-elev-1',
    '--cph-elev-2',
    '--cph-elev-3',
    '--cph-elev-4',
    '--cph-radius-sm',
    '--cph-radius-md',
    '--cph-radius-lg',
    '--cph-radius-full',
  ],
  motion: [
    '--cph-motion-fast',
    '--cph-motion-base',
    '--cph-motion-slow',
    '--cph-ease-standard',
    '--cph-ease-emphasized',
    '--cph-ease-octo',
  ],
  type: [
    '--cph-font-sans',
    '--cph-font-mono',
    '--cph-fs-xs',
    '--cph-fs-sm',
    '--cph-fs-md',
    '--cph-fs-lg',
    '--cph-fs-xl',
    '--cph-fs-2xl',
    '--cph-lh-tight',
    '--cph-lh-normal',
    '--cph-fw-regular',
    '--cph-fw-medium',
    '--cph-fw-bold',
  ],
} as const;
